global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "vtt-api"
    static_configs:
      - targets: ["localhost:8000"]
        labels:
          service: "witcher-vtt-api"
    metrics_path: "/metrics"
